### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by clintonb** [pinax/pinax-announcements#25]
Will you publish a new version on Git and to PyPI, please?

**Comment by zanderle** [comment]
+1

**Comment by failedguidedog** [comment]
+1

**Comment by paltman** [comment]
Will do this soon, but likely not as django-announcements but rather pinax-announcements with a package namespaced under `pinax.announcements` but I hope to do all this real soon.

**Comment by paltman** [comment]
I also would like #19 merge able first

**Comment by primoz-k** [comment]
Just checking, how is it going with this?

**Comment by oboyle** [comment]
:+1:

**Comment by mmcardle** [comment]
+1

**Comment by clintonb** [comment]
@paltman any update on the release? It's been a while.

**Comment by clintonb** [comment]
@ossanna16 I see you've been committing recently. Any plans to actually create a new release?

**Comment by brosner** [comment]
Some of the Pinax team will be at DjangoCon this next week. I will make sure either myself or someone else gets to this!

**Comment by epicserve** [comment]
@brosner and @paltman, FYI, when following the [docs](https://github.com/pinax/django-announcements/blob/master/docs/installation.rst) I used `pip install django-announcements` which installed a version that didn't work on Django 1.8.3. When I used `pip install 'https://github.com/pinax/django-announcements/archive/master.zip'` I was able to get it to work. So either the docs need to get updated or the version on PyPI needs updated.

**Comment by paltman** [comment]
@epicserve thanks for this report, i'll try to get to it this week

**Comment by clokep** [comment]
Just another point that there's now a deprecation warning with Django 1.9 for the version on pypi:
```
/venv/local/lib/python2.7/site-packages/announcements/urls.py:16: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name="announcements_delete"),
```

This seems to already be fixed in master, however! :smile:

**Comment by ossanna16** [comment]
@brosner @paltman Any updates regarding a new release or any further discussion on this?

**Comment by paltman** [comment]
@ossanna16 it's on the list for consideration for 16.4 distribution (https://github.com/pinax/pinax/issues/84#issuecomment-171067724), I hesitate to commit to anything else at this point based on the previous dropping of the ball on this thread by yours truly. :)

**Comment by ossanna16** [comment]
Sounds good 👍

**Comment by paltman** [comment]
2.0.0 is ready to push to PyPI. Just need @brosner to do it or for him to add me as a maintainer, but you can use the tag on this repo for now.

**Comment by brosner** [comment]
@paltman you should have access now.

**Comment by paltman** [comment]
[2.0.0](https://pypi.python.org/pypi/pinax-announcements/2.0.0) has been released / published.

**Comment by zanderle** [comment]
Yaaay! :)
