### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by MaZZly** [pinax/pinax-announcements#30]
When installing django-announcements my project stops running due to

`django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.`

and it's originating from `User = get_user_model()` in announcements/models.py

From my findings get_user_model() has to be run during runtime after  but not sure..

Any ideas how to fix this?

**Comment by ossanna16** [comment]
@MaZZly Would you mind joining our Pinax Slack team (http://slack.pinaxproject.com) and asking your question there? We are usually able to answer questions faster in Slack than here. Thank you! :)

**Comment by paltman** [comment]
This is no longer applicable.
