### ISSUE TITLE
Document how to find templates

### ISSUE THREAD

**Issue by craigds** [pinax/pinax-announcements#54]
When installing this app I get these cryptic errors:

> django.template.exceptions.TemplateDoesNotExist: pinax/announcements/announcement_list.html, announcements/announcement_list.html

Looks like #48 removed all the templates, and AFAICT the documentation has no advice on where to find them.

**Comment by ossanna16** [comment]
@brosner Can you help with this please?

**Comment by jtauber** [comment]
All templates (for any Pinax apps) are in pinax-theme-bootstrap.

I'll leave this open until we update docs to say this, though.

**Comment by jtauber** [comment]
fixed in #56
