### ISSUE TITLE
Mistake in snippet in Readme

### ISSUE THREAD

**Issue by armadarama** [pinax/pinax-announcements#62]
Hi

in the following code snippet in the readme you have announcement_list and announcementS_list, which results in no announcements displayed.
``    <h3>Announcements</h3>

    {% announcements as announcement_list %}

    {% if announcements_list %}
        <div class="announcements">
            {% for announcement in announcement_list %}
                <div class="announcement">
                    <strong>{{ announcement.title }}</strong><br />
                    {{ announcement.content }}
                </div>
            {% endfor %}
        </div>
    {% endif %}``

**Comment by KatherineMichel** [comment]
Thank you for letting us know @armadarama. I fixed the typo and will close the issue.
