### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by PeterTillema** [pinax/pinax-announcements#71]
`django.conf.urls.url()` got removed in Django 4.0, as seen here:
https://github.com/pinax/pinax-announcements/blob/ec0388595ea5c561a00e2c3ffa15dab513641c0e/pinax/announcements/urls.py#L1

Also, the `providing_args` argument for `django.dispatch.Signal` is removed as seen here: https://github.com/pinax/pinax-announcements/blob/ec0388595ea5c561a00e2c3ffa15dab513641c0e/pinax/announcements/signals.py#L3-L5

**Comment by tari** [comment]
`django.conf.urls.url` is a legacy alias for `django.urls.re_path` which was added in Django 2.0, so that should be a trivial conversion.

`providing_args` was never functional so those instances should simply be removed, possibly with description of the args added as comments.
